### ISSUE TITLE
[bug] Maps not accessible

### ISSUE THREAD

**Issue by LeoKotschenreuther** [hpi-swt2/event-und-raumplanung#204]
When I try to go to go to the maps page I receive an error.

![screen shot 2014-12-17 at 22 12 52](https://cloud.githubusercontent.com/assets/6781162/5479053/df97232e-8639-11e4-98e6-413b31ddd6c0.png)

**Comment by jaSunny** [comment]
@mweisz  what is the status here? shall i include it into dolphins sprint?

**Comment by mweisz** [comment]
@jaSunny Leo and I agreed that it would make sense to include an icon (or link) leading to the maps page  on the /rooms page. However, there currently seems to be a problem with the permission since you can only view the page when completely locked out. 
In a word: It would be great if you included these issues in Dolphin's sprint.
