### ISSUE TITLE
One Click Login (35 est.)

### ISSUE THREAD

**Issue by jaSunny** [hpi-swt2/event-und-raumplanung#217]
**As a user in want to be authenticated via OpenID without entering my email address to speed up the login experience.**

![217_one_click_login](https://cloud.githubusercontent.com/assets/3418034/5816487/fbee4ec2-a0a0-11e4-8c5d-342e3cc7745e.jpg)

**Acceptance Criteria:**
- [ ] Clicking the single login button directly redirects to the HPI OpenID provider page
- [ ] Email address should be requested in the initial wizard as a mandatory field when logging in for the first time and no email address is available via OpenID
- [ ] Email address must be a valid @hpi address

**Comment by jaSunny** [comment]
@leoselig your team?

**Comment by leoselig** [comment]
Mockup for workflow

**Comment by leoselig** [comment]
@Thulur 
added mockup

**Comment by mr-flannery** [comment]
@leoselig you've basically seen everything already, but it's in the dev now and as soon as somebody merges our PR the corresponding tests should be in the dev as well. So you might want do consider checking it out again, your choice.

**Comment by leoselig** [comment]
@philipp94831 Refering to your discussion with @Thulur About Whether or not the email address is mandatory or not
in general, email should be optional but we had some confusiomy whether this would lead to technical problems regarding, for instance, email notifications
Since you removed the obligation of having to enter an address I assume this has been verified by your tests sufficiently

**Comment by philipp94831** [comment]
@leoselig well it was not my task to implement something like that. I just refactored the profiles and there you can toggle email notifications. I think there are some tests but you have to ask @stephde and @domhey for details. I don't even know why the authentification has to bother about the profile system.

**Comment by leoselig** [comment]
If you are interested in why two parts of the system are technically or semantically connected I strongly recommend to ask a PO about that
Your misunderstandings regarding the specified workflows must never result in a feature not being implemented
There was an idea behind making the email mandatory but as I already said we can leave it the way it is now provided that defects are unlikely

**Comment by philipp94831** [comment]
Well I think the real problem here is that a user can only edit his own profile and this is not respected by the authentication system because they deal with temporary users as far as I think. I think this is what needs to be implemented better.

**Comment by leoselig** [comment]
I don't see why that limitation matters here, of course only the user can edit his profile
however, this is an implementation detail I'd ask you to discuss with your Scrum master and the responsible developers
@Atyanar @SvenLehmann 
@LeoKotschenreuther

**Comment by Thulur** [comment]
The problem is not about a user accessing anothers edit page. The current specification says a user can be created without an email, but he should not be able to interact with the system without a valid email address ("Email address should be requested in the initial wizard as a mandatory field"). The whole system should not be exposed to a user without a valid email, like it was done with the profile controller.
The point is should a missing email result in  a redirect to the user edit page (former profile page) or is a user allowed to use the system without the address (the current edit page says all fields are optional).
I was quite confused about the pull request (#328) some hours ago, which does exactly the opposite of what I wrote on Slack and the specification of this issue.

**Comment by Thulur** [comment]
With 2f9b47f5e8ae550e7e586aa9a605166ae217c4a3 the lines solving the problem where removed by a merge, without any further information. Due the fact the profile controller was finally removed and got replaced by an actual user edit this lines should be replaced by a current version to match the specs of this issue (assuming the message on the user edit page is just wrong).

**Comment by philipp94831** [comment]
Well the main problem was a redirect loop. I can try to fix it but a member of the team Bieber should be able to fix it faster and better because I have no idea of the specification or technical background

**Comment by philipp94831** [comment]
@leoselig @Thulur  Is 509f596e0cdb636e4759be89dc706728fc048a52 fixing everytihing sufficiently?

**Comment by Thulur** [comment]
In a local test case the system behaves like it was intended by us. The confusing flash message is still existing. I think we should not tell the user all fields are optional while the email is required to interact with the system.

**Comment by philipp94831** [comment]
The flash message was implemented by @DomHey and @stephde to match the requiremnts of @LeoKotschenreuther and #190 & #154
