### ISSUE TITLE
[SHOWSTOPPER] Login impossible

### ISSUE THREAD

**Issue by leoselig** [hpi-swt2/event-und-raumplanung#312]
Go the dev branch and try to login with you @hpi account, it will fail stating the credentials are invalid
Admin login works
(as of commit 4ded485516cbfc80cbb40ae5155a6a166d9804f0)

@DasDingGehtNicht @Atyanar @lulufaber @SvenLehmann @rosabraatz

**Comment by Thulur** [comment]
The login works again. The openid provider url was removed from the config.

**Comment by Atyanar** [comment]
A question for the tutors: How could you test something like this? 
To test the config for the existence of certain values doesn't strike me as particularly elegant...

**Comment by jaSunny** [comment]
i can confirm, login is working again. therefor close

**Comment by hubx** [comment]
@Atyanar This is not a bug you would find through unit tests, etc but more how the system deals/prevents with deployment misconfigurations. Two possible approaches to deal with such issues (generic answer, since I don't know what specific error was triggered, because no stacktrace was provided here and the heroku logs won't show it anymore)

1) See valid OpenID url required for the system. Don't start rails server unless valid identity URL is provided. (I can image a `check_openid_config`functionality is already implemented in devise_openid_authenticatable, e.g. for compatible openid version)
2) See OpenID of HPI as requirement for the system: write a unit test that for the user 'hubert.hesse' the correct indentity url `https://openid.hpi.uni-potsdam.de/user/hubert.hesse` is provided

Bonus: Think about what happens if the openid server is not reachable and how your system reacts.

**Comment by jaSunny** [comment]
just want to mention, there is an Acceptance Test, which is testing the Login functionality

https://github.com/hpi-swt2/event-und-raumplanung/blob/PO-acceptance-Sprint3/spec/acceptance/signin_feature_spec.rb

```ruby
scenario "Signing in with correct eMail" do
    page.visit "/users/sign_in"
    page.should have_text("Log in")
    page.fill_in "user_email", :with => "Max.Mustermann@student.hpi.de"
    page.click_button "Log in"
    expect(page.current_url).to eq "https://openid.hpi.uni-potsdam.de/serve"
end
```

**Comment by hubx** [comment]
@jaSunny So why is this not included in dev? In fact there no acceptance test in [dev](/hpi-swt2/event-und-raumplanung/tree/dev/spec/)?

**Comment by leoselig** [comment]
I was about to write the same
We should definitely push forward the merge of the acc tests this week
especially with an eye toward a the final presentation ;)

**Comment by leoselig** [comment]
For the record, I wanted to reply to @jaSunny

**Comment by jaSunny** [comment]
@hubx because the scrum masters didnt want to merge it in the beginning of the sprint because then the branch would fail until end of the sprint. As far as i understood it, the plan was to merge the dev in the PO-acceptance branch check if all tests passes and then merge it back in dev. or am i wrong?
@leoselig yea, i see it the same way..

**Comment by hubx** [comment]
@jaSunny I don't see why acceptance tests should be treated differently from other tests. Ideally, as a PO you commit the test to your team's branch at the beginning of the sprint. As a result your team will know what to implement and will fix the code accordingly. At the end your changes will be merged to dev/master and prevent that your feature breaks in the future, e.g. through merges (like this ticket)

At the moment, does your team know that there is branch/feature-acceptence-test that has to be integrated? If so, did you acquire hours so they can do it in Sprint 4? 

The idea is not that you write the acceptance tests after the sprint is finished and fix the implementation on your own.

**Comment by tkowark** [comment]
@hpi-swt2/product-owners-2014 @hpi-swt2/biber-dev-14 @hpi-swt2/axolotl-dev-14 @hpi-swt2/clownfisch-dev-14 @hpi-swt2/delfin-dev-14 @hpi-swt2/elch-dev-14 Maybe out would be worthwhile to include the POs acceptance tests into your respective team branches ^^ 

If you are concerned about the branches being "red" all the time, you could tag the acceptance tests and exclude them from being run on the CI Server: http://stackoverflow.com/questions/5069677/how-do-i-run-only-specific-tests-in-rspec

Once you've implemented all functionality required for a certain acceptance test, you simply remove the tag...

**Comment by jaSunny** [comment]
@hubx  I totally agree with you. yes, we mentioned it (at least I did) in Sprint planning 3 and 4. And we planned ~8 SP for bugs, improvements and merging conflicts.

> The idea is not that you write the acceptance tests after the sprint is finished and fix the implementation on your own.
Again, I totally agree. We wanted to hand in BDD tests later for sprint 1 & 2.

**Comment by SvenLehmann** [comment]
it would be nice if the POs could add these tags in the PO-branch, otherwise every team would have to add the tags on their own... merge conflicts would be inevitable
