### ISSUE TITLE
Automatically mark own event as favorite upon creation

### ISSUE THREAD

**Issue by leoselig** [hpi-swt2/event-und-raumplanung#354]
Read the title

**Comment by mr-flannery** [comment]
@leoselig I have no time to finish this issue right now, sry.
I tried the following: in the events_controller there's a function called toggle_favorite (which is called by show_toggle_favorite, so the latter seems irrelevant to me). When I call this message while creating a new event, the only thing that happens is that instead of favoriting the event, the star/button that triggers favoriting from the ui just disappears. And I have no idea why. So maybe someone who's familiar with the code should look into it. Just my 2cts.

**Comment by leoselig** [comment]
Re-assigned to @github1992 due to timing issues in team Biber

**Comment by github1992** [comment]
Needs to be reviewed at http://fab-swt.herokuapp.com/ as I did not want to push to dev during the review of other teams.

**Comment by leoselig** [comment]
Just reviewed, looks good, feel free to create PR
